apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: fastapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastapi
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: fastapi
    spec:
      containers:
      - name: fastapi
        image: ghcr.io/mycodedynamic/fastapi-services:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
        ports:
          - containerPort: 8000
